Name:           perl-Parse-EDID
Version:        1.0.6
Release:        2%{?dist}
Summary:        Extended display identification data (EDID) parser
License:        GPLv3
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Parse-EDID/
Source0:        http://www.cpan.org/authors/id/G/GR/GROUSSE/Parse-EDID-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More) >= 0.93
BuildRequires:  perl(Test::Kwalitee)
BuildRequires:  perl(Test::Pod)
BuildRequires:  perl(Test::Pod::Coverage)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module provides some function to parse Extended Display Identification
Data binary data structures.

%prep
%setup -q -n Parse-EDID-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
make pure_install DESTDIR=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%files
%doc Changes LICENSE README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Jun 11 2014 Marianne Lombard <marianne@tuxette.fr> - 1.0.6-2
- adding missing buildrequires
- continuing adapting spec to actul guidelines

* Wed May 21 2014 Marianne Lombard <marianne@tuxette.fr> - 1.0.6-1
- Adapting spec to actual guidelines
- Specfile autogenerated by cpanspec 1.78.
